[build]
  command = "yarn build:docs"
  publish = "docs/dist"

[build.environment]
  YARN_VERSION = "1.7.0"
  
# The following redirect is intended for use with most SPA's that handles routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
